# Generated by Django 5.1.3 on 2024-11-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default=True, upload_to='media/'),
            preserve_default=False,
        ),
    ]
